spring:
  application:
    name: spring-jwt
  datasource:
    url: jdbc:h2:file:./data/demo;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:

    console:
      enabled: true
      path: /h2-console

logging:
    level:
        root: INFO
        org.springframework.security: DEBUG